[keyboard]
bindings = [
  { key = "Return", mods = "Control|Shift", action = "SpawnNewInstance" }
]

[window]
opacity = 0.9
padding = { x = 0, y = 0 }
decorations = "full"

[font]
size = 11.0

# [general]
# import = [
# 	"~/.config/alacritty/themes/themes/solarized_light.toml"
# ]

[colors.normal]
black = '#f2f2f2'
red = '#a60000'
green = '#006800'
yellow = '#6f5500'
blue = '#0031a9'
magenta = '#721045'
cyan = '#005e8b'
white = '#000000'
[colors.bright]
black = '#c4c4c4'
red = '#a0132f'
green = '#00663f'
yellow = '#7a4f2f'
blue = '#0000b0'
magenta = '#531ab6'
cyan = '#005f5f'
white = '#595959'
[colors.cursor]
cursor = '#000000'
text = '#ffffff'
[colors.primary]
background = '#ffffff'
foreground = '#000000'
[colors.selection]
background = '#bdbdbd'
text = '#000000'




# # Colors Modus-Vivendi
# [colors.normal]
# black = '#1e1e1e'
# red = '#ff5f59'
# green = '#44bc44'
# yellow = '#d0bc00'
# blue = '#2fafff'
# magenta = '#feacd0'
# cyan = '#00d3d0'
# white = '#ffffff'
# [colors.bright]
# black = '#535353'
# red = '#ff7f9f'
# green = '#00c06f'
# yellow = '#dfaf7a'
# blue = '#00bcff'
# magenta = '#b6a0ff'
# cyan = '#6ae4b9'
# white = '#989898'
# [colors.cursor]
# cursor = '#ffffff'
# text = '#000000'
# [colors.primary]
# background = '#000000'
# foreground = '#ffffff'
# [colors.selection]
# background = '#5a5a5a'
# text = '#ffffff'
#
#

