#!/usr/bin/env bash

work=${1:-25}
break=${2:-5}
cycles=${3:-0} 

cleanup () {
    tput cnorm
}
trap cleanup EXIT
trap "cleanup; exit 130" INT TERM

countdown () {
    local seconds=$(( $1 * 60 ))
    local label=$2

    tput civis 
    while [ $seconds -gt 0 ]; do
        tput clear
        tput cup 0 0
        printf "%s: %02d:%02d\n" "$label" $((seconds/60)) $((seconds%60))
        sleep 1
        ((seconds--))
    done
    tput cnorm  
}

run_cycle () {
    countdown "$work" "Work"
    notify-send "Pomodoro" "Done :)"

    countdown "$break" "Break"
    notify-send "Pomodoro" "Back to work >:|"
}

if [ "$cycles" -eq 0 ]; then
    while true; do
        run_cycle
    done
else
    for ((i=1; i<=cycles; i++)); do
        run_cycle
    done
fi
i
